### ISSUE TITLE
Restart master cause listStatus return local directory content, instead of from UFS

### ISSUE THREAD

**Issue by lichaoguang973** [Alluxio/alluxio#8720] opened 2019-04-08 14:43 UTC
**Alluxio Version:**
2.0.0-preview
**Describe the bug**
start a single master (without zk) in docker, after a successful ls in client (Kodo client), restart master and re-mount UFS to master, then ls, will see the listStatus return / in docker env.
**To Reproduce**
1. start one worker, one master, and one client with fuse (with kodo, oss or other may work)
2. mkdir -f /fuse in client fuse
3. mount an bucket to master in fuse (/opt/alluxio/integration/bin/alluxio-fuse mount /fuse /
4. mount bucket to master (i use kodo)
5. cd to the mount point and ls; with a clean start, it works
6. restart master & client 
7. remount client to master with step 2-4
8. cd to mount point and ls
**Expected behavior**
ls will return the content in UFS, not from master local dir
**Urgency**
alluxio will crash after master restart
**Additional context**

**Comment by aaudiber** [comment] 2019-04-08 17:29
@lichaoguang973 which part of alluxio crashes? The fuse client, the master, or the worker (or all)? Is there any sort of error message, either on from the CLI or from the logs?

**Comment by lichaoguang973** [comment] 2019-04-08 23:12
Alluxio didn't crash. It just return the local file list in where alluxio master is deployed. There is not error message in the log. It seems like the master gets a wrong UnderFileSystem, aka, it gets a LocalUnderFileSystem instead of KodoUderFileSystem or some other UFS UnderFileSYstem.

**Comment by aaudiber** [comment] 2019-04-09 16:53
@lichaoguang973 When you restart master & client, are you starting a new Docker container? How are you mounting kodo into Alluxio? Can you share more details on the commands you ran so I can try to reproduce the issue?

**Comment by guang7niu** [comment] 2019-04-16 13:56
Sorry for late response. I mount /opt/alluxio from mac to docker, so the /opt/alluxio/journal folder is also mounted into docker. I restart master by just restarting the docker (docker rm -f alluxio-master, and then docker run command to start the master). But again, the /opt/alluxio/journal is also mounted into the docker environment.

**Comment by gpang** [comment] 2019-04-16 19:59
@guang7niu @lichaoguang973 Why do you have to re-mount the UFS? If the master is replaying from an existing journal, then nothing should be re-mounted, since the mount information is already in the journal.

**Comment by guang7niu** [comment] 2019-04-17 01:53
Try again, the journal is loaded. The reason is probably that journal is corrupted during the shutdown or  docker restart operation. Now verified that the journal is ok and mount point successfully get mounted back into master. Thanks. We can close this issue.

**Comment by gpang** [comment] 2019-04-17 15:02
@guang7niu Thanks for the update!

**Closed by gpang** 2019-04-17 15:02 UTC
Labels: area-master, target-2.0.0, type-bug
