### ISSUE TITLE
Single-Tier Storage configuration is not working 

### ISSUE THREAD

**Issue by perrywang** [Alluxio/alluxio#8687] opened 2019-04-04 12:16 UTC
**Alluxio Version:**
1.8.1
**Describe the bug**
following https://www.alluxio.org/docs/1.8/en/advanced/Alluxio-Storage-Management.html#single-tier-storage
config below in alluxio-site.properties
alluxio.worker.memory.size=16GB
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk,/home/hdd
alluxio.worker.tieredstore.level0.dirs.quota=16GB,200GB
but the worker create below ramfs mount point
**/mnt/ramdisk,/home/hdd**
the comma is as part of directory name of **ramdisk,**

**To Reproduce**
config as above and start worker

**Expected behavior**
working consistent with doc
https://www.alluxio.org/docs/1.8/en/advanced/Alluxio-Storage-Management.html#single-tier-storage

**Urgency**
intermediate
**Additional context**
N/A

**Comment by aaudiber** [comment] 2019-04-04 19:49
@perrywang thanks for reporting this. I tried it out locally and I can reproduce the problem.

There is a check in the start script which reads `level0.dirs.path` and checks that the path exists or the worker will try to mount it. To work around the issue, you can mount the ramdisk beforehand, then start the worker with `bin/alluxio-start.sh worker NoMount`. For this to work, comment out this check in `alluxio-start.sh`:
https://github.com/Alluxio/alluxio/blob/branch-1.8/bin/alluxio-start.sh#L109

**Comment by perrywang** [comment] 2019-04-05 09:00
> @perrywang thanks for reporting this. I tried it out locally and I can reproduce the problem.
> 
> There is a check in the start script which reads `level0.dirs.path` and checks that the path exists or the worker will try to mount it. To work around the issue, you can mount the ramdisk beforehand, then start the worker with `bin/alluxio-start.sh worker NoMount`. For this to work, comment out this check in `alluxio-start.sh`:
> https://github.com/Alluxio/alluxio/blob/branch-1.8/bin/alluxio-start.sh#L109

I can manually mount ramfs but workaround is not working because NoMount will ignore /home/hdd

**Comment by aaudiber** [comment] 2019-04-05 18:13
@perrywang I tried it out locally with this configuration:

```
alluxio.master.hostname=localhost
alluxio.worker.tieredstore.level0.dirs.path=/Volumes/ramdisk,/Users/andrew/hdd
alluxio.worker.tieredstore.level0.dirs.quota=2GB,10GB
```

When I write a 10GB file, it puts most of the blocks under /Users/andrew/hdd, and the rest under /Volumes/ramdisk. The alluxio.worker.allocator.class property controls the policy for where to write blocks among the storage tiers.

**Comment by perrywang** [comment] 2019-04-06 03:24
@aaudiber I will try your test

**Comment by perrywang** [comment] 2019-04-08 03:49
> alluxio.master.hostname=localhost
> alluxio.worker.tieredstore.level0.dirs.path=/Volumes/ramdisk,/Users/andrew/hdd
> alluxio.worker.tieredstore.level0.dirs.quota=2GB,10GB

@aaudiber I test below configurations
alluxio.master.hostname=localhost
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk,/mnt/hdd
alluxio.worker.tieredstore.level0.dirs.quota=1GB,10GB

I pre manually mount ramdisk with command
1.  `mount -t ramfs -o size=1GB ramfs /mnt/ramdisk`
2. comment out you mentioned mount check in alluxio-start.sh
3. run `alluxio-start.sh worker NoMount`
4. add some files to alluxio.
5. result is all the blocks existing under /mnt/hdd but no blocks in /mnt/ramdisk. It is different with you mentioned there are some blocks can be assign under /mnt/ramdisk

**Comment by perrywang** [comment] 2019-04-08 04:24
@aaudiber 
I find another fact that after the size of files over /mnt/hdd quote, in this case 10G, the new block is indeed allocated at /mnt/ramdisk. So alluxio is prefer to use hdd as lower storage? Need a behavior confirm to explain. If alluxio prefer hdd is it will affect IO performance?

**Comment by aaudiber** [comment] 2019-04-08 17:43
@perrywang yes, MaxFreeAllocator will use whichever directory has the most space available. Since the hdd dir is much bigger than the ramdisk, all blocks will go to the hdd until they have the same amount of space left. To prioritize using the ramdisk, try setting `alluxio.worker.allocator.class=alluxio.worker.block.allocator.GreedyAllocator` instead of the default

**Comment by perrywang** [comment] 2019-04-09 02:35
> @perrywang yes, MaxFreeAllocator will use whichever directory has the most space available. Since the hdd dir is much bigger than the ramdisk, all blocks will go to the hdd until they have the same amount of space left. To prioritize using the ramdisk, try setting `alluxio.worker.allocator.class=alluxio.worker.block.allocator.GreedyAllocator` instead of the default

@aaudiber I have applied GreedyAllocator in an environment. After run a IO intensive job，there is a warning in worker log
`Failed to cache data read from UFS (on read()): Failed to request 8388608 bytes after 10,000ms to create blockId 307895468032`
And after checking ramdisk with` du -h` I found it is used over its quote a little bit. I set quote is 13GB, and `du -h` show it used 14G. Is this warning related with this ?

**Comment by apc999** [comment] 2020-11-20 20:09
Addressed by https://github.com/Alluxio/alluxio/pull/12182

**Closed by apc999** 2020-11-20 20:09 UTC
Labels: area-shell, priority-high, type-bug

**Comment by apc999** [comment] 2020-11-25 19:20
A test is added https://github.com/Alluxio/alluxio/pull/11743 to enforce this case working
