### ISSUE TITLE
work load data fail (temp blockId xxx is not available, because it is already committed)

### ISSUE THREAD

**Issue by wwq2333** [Alluxio/alluxio#18042] opened 2023-08-22 02:49 UTC
**Alluxio Version:**
2.9.3

**Describe the bug**

use `fs loadmeta` and `fs load` to warmup alluxio cache;
loadmeta can be successfully completed but load data run failed;

```
Progress for loading path '/':
	Settings:	bandwidth: unlimited	verify: false
	Job State: FAILED (alluxio.exception.runtime.InternalRuntimeException: Job failed because it's not healthy.)
	Files Processed: 4905236
	Bytes Loaded: 412.81GB
	Throughput: 451.62MB/s
	Block load failure rate: 5.20%
	Files Failed: 9699
```

worker err log
```
java.lang.IllegalStateException: Temp blockId 80595296190464 is not available, because it is already committed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
	at alluxio.worker.block.TieredBlockStore.checkBlockDoesNotExist(TieredBlockStore.java:549)
	at alluxio.worker.block.TieredBlockStore.createBlockMetaInternal(TieredBlockStore.java:710)
	at alluxio.worker.block.TieredBlockStore.createBlock(TieredBlockStore.java:289)
	at alluxio.worker.block.MonoBlockStore.load(MonoBlockStore.java:328)
	at alluxio.worker.block.DefaultBlockWorker.load(DefaultBlockWorker.java:448)
	at alluxio.worker.grpc.BlockWorkerClientServiceHandler.load(BlockWorkerClientServiceHandler.java:179)
	at alluxio.grpc.BlockWorkerGrpc$MethodHandlers.invoke(BlockWorkerGrpc.java:881)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Additional context**

- ufs fileCount: 10889213, fileSize 859.66 GB
- `/cover` contains 800,000 folders, each folder has about 10~20 pictures
- other files in `/` is annotation (.txt)

**Comment by ssz1997** [comment] 2023-08-25 17:28
@jja725 FYI

**Comment by jja725** [comment] 2023-08-25 18:39
The error seems like we failed at certain files and tried to load them again. It would be great if we can have the test data since it's reproducible.

**Comment by Haoning-Sun** [comment] 2023-09-05 11:01
It can be fixed by https://github.com/Alluxio/alluxio/pull/17735

**Comment by jja725** [comment] 2023-09-08 17:58
fixed by https://github.com/Alluxio/alluxio/pull/17735

**Closed by jja725** 2023-09-08 17:58 UTC
Labels: type-bug
