### ISSUE TITLE
Automatically restart worker

### ISSUE THREAD

**Issue by Trevor-zhang** [Alluxio/alluxio#11785] opened 2020-07-20 11:46 UTC
**Alluxio Version:**
What version of Alluxio are you using?
2.2.0
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by miaomiao2miaomiao** [comment] 2020-07-20 11:48
When the alluxio worker hangs, the worker cannot restart automatically.
where to find the log can check the wrong log? worker.out does not provide useful information.

**Comment by miaomiao2miaomiao** [comment] 2020-07-20 12:03
When a query with a large amount of data is executed, the worker will start reporting errors, and then will hang. May I ask what causes this?

`20/07/20 19:59:48 WARN scheduler.TaskSetManager: Lost task 764.0 in stage 0.0 (TID 658, xx-xxxxx-cdh-data02, executor 2): ExecutorLostFailure (executor 2 exited caused by one of the running tasks) Reason: Container marked as failed: container_e55_1595210726042_0023_01_000003 on host: xx-xxxxx-cdh-data02. Exit status: 137. Diagnostics: [2020-07-20 19:59:48.259]Container killed on request. Exit code is 137
[2020-07-20 19:59:48.263]Container exited with a non-zero exit code 137. 
[2020-07-20 19:59:48.264]Killed by external signal`

**Comment by miaomiao2miaomiao** [comment] 2020-07-20 12:09
![image](https://user-images.githubusercontent.com/33487819/87936125-e570d800-cac4-11ea-9c59-7ec7f26842a0.png)

**Closed** 2021-06-22 14:18 UTC
Labels: type-bug
