### ISSUE TITLE
Alluxio fuse kubernetes deployment can not read/write file when using jnifuse

### ISSUE THREAD

**Issue by AlexChenSkyBlue** [Alluxio/alluxio#13413] opened 2021-05-14 04:05 UTC
**Alluxio Version:**
What version of Alluxio are you using?
2.5.0 - *
**Describe the bug**
cp: error reading '123.txt': Input/output error. when we use below setting in kubernetes helm deployment. 
  properties:
    alluxio.fuse.jnifuse.enabled: "true" 
    alluxio.fuse.shared.caching.reader.enabled: "true"
    alluxio.fuse.debug.enabled: "true" 
    alluxio.fuse.cached.paths.max: "3000000"
    alluxio.fuse.logging.threshold: 1000ms
    alluxio.fuse.user.group.tranlation.enabled: "true"
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
helm install using above properties
**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by AlexChenSkyBlue** [comment] 2021-05-14 07:07
详细报错信息：
2021-05-14 06:54:08,594 ERROR AlluxioJniFuseFileSystem - Failed to read, path: /data/model-iteration/1.txt size: 4096 offset: 0
java.lang.ClassCastException: alluxio.client.file.cache.LocalCacheFileInStream cannot be cast to alluxio.client.file.AlluxioFileInStream
	at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:429)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:404)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:280)
	at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:404)
	at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:180)
   unique: 1369, error: -5 (Input/output error), outsize: 16
unique: 1370, opcode: FLUSH (25), nodeid: 9, insize: 64, pid: 35513

**Comment by apc999** [comment] 2021-05-20 20:51
@AlexChenSkyBlue  this issue is a duplicate of https://github.com/Alluxio/alluxio/issues/13442
@maobaolong  is working on addressing that issue. 
Closing this issue and we can transfer discussions there

**Closed by apc999** 2021-05-20 20:51 UTC
Labels: type-bug
