### ISSUE TITLE
Alluxio replicates the block repeatedly without committing it

### ISSUE THREAD

**Issue by secfree** [Alluxio/alluxio#15912] opened 2022-07-19 08:29 UTC
**Alluxio Version:**
2.7.1

**Describe the bug**
Alluxio replicates the block repeatedly without committing it

**To Reproduce**
1. The file has 1 existing replica

```
$ ./bin/alluxio fs location /projects/test/test_dir/file.1
/projects/test/test_dir/file.1 with file id 134939148287 is on nodes:
dev01-xx
```

2. Set replicationMin to 2 and pin the file

```
$ ./bin/alluxio fs setReplication --min 2 /projects/test/test_dir/file.1
$ ./bin/alluxio fs pin /projects/test/test_dir/file.1
```

3. Alluxio replicates the file repeatedly without committing it

```
2022-07-19 15:55:56,690 INFO  task.TaskExecutorManager (TaskExecutorManager.java:executeTask) - Task 0 for job 1652866638371 received
2022-07-19 15:55:56,690 INFO  task.TaskExecutorManager (TaskExecutorManager.java:notifyTaskRunning) - Task 0 for job 1652866638371 started
2022-07-19 15:55:56,741 INFO  replicate.ReplicateDefinition (ReplicateDefinition.java:runTask) - Replicated file /projects/test/test_dir/file.1 block 134922371072
2022-07-19 15:55:56,742 INFO  task.TaskExecutorManager (TaskExecutorManager.java:notifyTaskCompletion) - Task 0 for job 1652866638371 completed.
2022-07-19 15:56:56,692 INFO  command.CommandHandlingExecutor (CommandHandlingExecutor.java:run) - Received run task 0 for job 1652866638372 on worker 1652866621069
2022-07-19 15:56:56,692 INFO  task.TaskExecutorManager (TaskExecutorManager.java:executeTask) - Task 0 for job 1652866638372 received
2022-07-19 15:56:56,693 INFO  task.TaskExecutorManager (TaskExecutorManager.java:notifyTaskRunning) - Task 0 for job 1652866638372 started
2022-07-19 15:56:56,763 INFO  replicate.ReplicateDefinition (ReplicateDefinition.java:runTask) - Replicated file /projects/test/test_dir/file.1 block 134922371072
2022-07-19 15:56:56,763 INFO  task.TaskExecutorManager (TaskExecutorManager.java:notifyTaskCompletion) - Task 0 for job 1652866638372 completed.
```

**Expected behavior**
Commit the block and do not replicate it repeatedly.

**Urgency**
High

**Are you planning to fix it**
Yes

**Comment by secfree** [comment] 2022-07-19 08:30
The cause is this PR: #13146.
It removed `BlockOutStream` which calls `DataWriter`, while `BlockWorkerDataWriter#close` calls `DefaultBlockWorker#commitBlock`.

**Comment by secfree** [comment] 2022-07-19 09:47
`AlluxioFileInStream` supports passive cache and calls `DefaultBlockWorker#cache` for each block, but `BlockInStream` itself does not support passive cache.

**Comment by yuzhu** [comment] 2022-07-19 17:15
@jja725 could you take a look please?

**Comment by jja725** [comment] 2022-07-19 18:19
thanks for raising the issue and I would take a look at this.

**Comment by secfree** [comment] 2022-07-20 02:24
> are you planning on fixing it?

Yes, my idea is to make `BlockInStream` support passive cache.
Do you have any suggestions? @jja725

**Comment by jja725** [comment] 2022-07-21 22:11
@secfree Hi, thanks for the invesitigation. I feel like we are taking a detour here to use passive cache to load data. The easiest way I think is to commit the block after writing the data. Otherwise, we need to take care of the passive cache in both AlluxioFileInStream and BlockInStream which may cause some problems.

**Comment by secfree** [comment] 2022-07-22 10:20
@jja725 thanks for your reply.

> The easiest way I think is to commit the block after writing the data. 
If `BlockOutStream` is created, it will commit block automatically. But #13146 already removed `BlockOutStream`.

> Otherwise, we need to take care of the passive cache in both AlluxioFileInStream and BlockInStream which may cause some problems.
Can you check my PR(#15918)? It moved passive cache logic from AlluxioFileInStream to BlockInStream.

**Comment by jja725** [comment] 2022-07-22 18:53
@secfree I think when the file is pinned, it would go through the code 161 to 193 in the JobUtils.java. So we are actually using inStream and BlockOutStream to load the file into his specific location. 
Yeah I agree move passive cache to BlockInStream  would solve this problem, but it would a read operation and it's not efficient

**Comment by secfree** [comment] 2022-07-23 10:52
> I think when the file is pinned, it would go through the code 161 to 193 in the JobUtils.java.

Have you tested it? In my test case mentioned above, it went to this branch https://github.com/Alluxio/alluxio/blob/master/job/server/src/main/java/alluxio/job/util/JobUtils.java#L154

**Comment by secfree** [comment] 2022-07-23 15:48
Another idea is disabling passive cache for pinned files. It also resolves the issue. Here is the PR: #15946 .
@jja725 what do you think about this? Thank you.

**Comment by yuzhu** [comment] 2022-07-27 22:01
@jja725 any thoughts on the PR?

**Comment by jja725** [comment] 2022-07-28 05:52
@secfree  I leave a slack message to you and want to record it here as well. 
I tested it again on my local machine and It works fine with the most updated version(1 worker with 1 replication). So want to double check your env. If you only have one worker and want to have two replicas, which is not allowed by the worker.

**Comment by secfree** [comment] 2022-07-28 13:57
@jja725 I tested with two workers, and confirmed that the replication task was received by the job_worker in the second worker. The log is also from the second worker

```
2022-07-19 15:55:56,690 INFO  task.TaskExecutorManager (TaskExecutorManager.java:executeTask) - Task 0 for job 1652866638371 received
2022-07-19 15:55:56,690 INFO  task.TaskExecutorManager (TaskExecutorManager.java:notifyTaskRunning) - Task 0 for job 1652866638371 started
2022-07-19 15:55:56,741 INFO  replicate.ReplicateDefinition (ReplicateDefinition.java:runTask) - Replicated file /projects/test/test_dir/file.1 block 134922371072
2022-07-19 15:55:56,742 INFO  task.TaskExecutorManager (TaskExecutorManager.java:notifyTaskCompletion) - Task 0 for job 1652866638371 completed.
...
2022-07-19 15:56:56,763 INFO  replicate.ReplicateDefinition (ReplicateDefinition.java:runTask) - Replicated file /projects/test/test_dir/file.1 block 134922371072
2022-07-19 15:56:56,763 INFO  task.TaskExecutorManager (TaskExecutorManager.java:notifyTaskCompletion) - Task 0 for job 1652866638372 completed.
```

**Comment by jja725** [comment] 2022-08-04 08:24
sorry for the delay, when I tried to reproduce the problem I noticed that the block actually gets committed in one worker but can't get committed in the other workers which I think neither of the fixes explains the problem. I think I need more time figuring out the bug but I feel OK with disabling passive cache solution for now since it indeed resolves the problem.

**Comment by secfree** [comment] 2022-08-04 08:36
@jja725 thanks for your checking. 
In my test case, he first replica of the block in alluxio was wrote by client directly. So it does not involve "passive cache". `setReplication` copies the block from the first worker to a new one, that is where passive cache takes effect.

**Comment by jja725** [comment] 2022-08-04 08:52
Thanks for digging into the issue and help me understand the problem. 
@yuzhu I think this also tells why distributedLoad with replications doesn't work very well(https://github.com/Alluxio/alluxio/issues/14274) because it doesn't commit the block when reading from the remote worker. We should add back the commit call when reading from the remote worker.

**Closed** 2022-08-09 02:37 UTC
Labels: priority-high, area-core, type-bug, area-master, area-worker
