### ISSUE TITLE
Kerberos authentication at HdfsUnderFileSystem constructor

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9398] opened 2019-07-01 23:07 UTC
**Alluxio Version:**
2.0.0

**Describe the bug**
Originally reported here: 
https://groups.google.com/forum/#!topic/alluxio-users/TcInse1vblc

**To Reproduce**

**Expected behavior**

**Urgency**
High

**Additional context**

**Comment by jiacheliu3** [comment] 2019-08-08 20:34
Original reported [issue](https://groups.google.com/forum/#!topic/alluxio-users/TcInse1vblc)

Not able to reproduce the issue as described. Pending on the reporter's response for more details. This issue will be closed if no user response in a period of time.

**Comment by jiacheliu3** [comment] 2019-09-01 18:45
I wasn't able to reproduce this issue. Here's what I did:
1. Connect Alluxio to secure HDFS. Alluxio version 2.0.0-RC4. This is done following guide Alluxio connect to secure HDFS.
2. Start spark shell specifying principal and keytab "spark-shell --principal hdfs/alluxio@ALLUXIO.COM --keytab {path_to_keytab}/alluxio.keytab"
3. Read and write parquet file from and to Alluxio and HDFS. I was able to do both without running into the exception in Alluxio BlockInputStream.

Closing this ticket since I don't have enough information. I'll re-open it if the original reporter replies and provides more details.

**Closed** 2019-09-01 18:46 UTC
Labels: area-ufs, priority-high, target-2.1.0, type-bug
