### ISSUE TITLE
Aliyun OSS Failed to get Object images_$folder$, return null

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10019] opened 2019-10-02 03:49 UTC
**Alluxio Version:**
2.1.0

**Describe the bug**

Seems `images_$folder$` is considering as object key. Any suggestions on this?

```
2019-10-02 03:35:06,344 INFO  oss - [Server]Unable to execute HTTP request: Not Found
[ErrorCode]: NoSuchKey
[RequestId]: 5D941AEA4D22F65A8496FF89
[HostId]: null
2019-10-02 03:35:06,345 WARN  OSSUnderFileSystem - Failed to get Object images_$folder$, return null
com.aliyun.oss.OSSException: Not Found
[ErrorCode]: NoSuchKey
[RequestId]: 5D941AEA4D22F65A8496FF89
[HostId]: null
	at com.aliyun.oss.common.utils.ExceptionFactory.createOSSException(ExceptionFactory.java:105)
	at com.aliyun.oss.internal.OSSErrorResponseHandler.handle(OSSErrorResponseHandler.java:56)
	at com.aliyun.oss.common.comm.ServiceClient.handleResponse(ServiceClient.java:257)
	at com.aliyun.oss.common.comm.ServiceClient.sendRequestImpl(ServiceClient.java:140)
	at com.aliyun.oss.common.comm.ServiceClient.sendRequest(ServiceClient.java:70)
	at com.aliyun.oss.internal.OSSOperation.send(OSSOperation.java:83)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:145)
	at com.aliyun.oss.internal.OSSObjectOperation.getObjectMetadata(OSSObjectOperation.java:496)
	at com.aliyun.oss.OSSClient.getObjectMetadata(OSSClient.java:602)
	at com.aliyun.oss.OSSClient.getObjectMetadata(OSSClient.java:592)
	at alluxio.underfs.oss.OSSUnderFileSystem.getObjectStatus(OSSUnderFileSystem.java:242)
	at alluxio.underfs.ObjectUnderFileSystem.isDirectory(ObjectUnderFileSystem.java:574)
	at alluxio.underfs.UnderFileSystemWithLogging$28.call(UnderFileSystemWithLogging.java:513)
	at alluxio.underfs.UnderFileSystemWithLogging$28.call(UnderFileSystemWithLogging.java:510)
	at alluxio.underfs.UnderFileSystemWithLogging.call(UnderFileSystemWithLogging.java:949)
	at alluxio.underfs.UnderFileSystemWithLogging.isDirectory(UnderFileSystemWithLogging.java:510)
	at alluxio.concurrent.ManagedBlockingUfsForwarder$23.execute(ManagedBlockingUfsForwarder.java:324)
	at alluxio.concurrent.ManagedBlockingUfsForwarder$23.execute(ManagedBlockingUfsForwarder.java:321)
	at alluxio.concurrent.ManagedBlockingUfsForwarder$ManagedBlockingUfsMethod.block(ManagedBlockingUfsForwarder.java:596)
	at alluxio.concurrent.jsr.ForkJoinPool.managedBlock(ForkJoinPool.java:1004)
	at alluxio.concurrent.ForkJoinPoolHelper.safeManagedBlock(ForkJoinPoolHelper.java:41)
	at alluxio.concurrent.ManagedBlockingUfsForwarder$ManagedBlockingUfsMethod.get(ManagedBlockingUfsForwarder.java:582)
	at alluxio.concurrent.ManagedBlockingUfsForwarder.isDirectory(ManagedBlockingUfsForwarder.java:326)
	at alluxio.master.file.DefaultFileSystemMaster.prepareForMount(DefaultFileSystemMaster.java:2650)
	at alluxio.master.file.DefaultFileSystemMaster.mountInternal(DefaultFileSystemMaster.java:2796)
	at alluxio.master.file.DefaultFileSystemMaster.mountInternal(DefaultFileSystemMaster.java:2761)
	at alluxio.master.file.DefaultFileSystemMaster.mount(DefaultFileSystemMaster.java:2737)
	at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$mount$9(FileSystemMasterClientServiceHandler.java:236)
	at alluxio.RpcUtils.callAndReturn(RpcUtils.java:113)
	at alluxio.RpcUtils.call(RpcUtils.java:78)
	at alluxio.RpcUtils.call(RpcUtils.java:53)
	at alluxio.master.file.FileSystemMasterClientServiceHandler.mount(FileSystemMasterClientServiceHandler.java:235)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2102)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:57)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
	at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
	at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1355)
	at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by JiamingMai** [comment] 2022-08-08 06:33
Does this issue still exist? It seems that this issue no longer exists any more. I cannot reproduce this in Alluxio 2.8.0. Consider to close this issue.

**Closed** 2022-08-19 06:02 UTC
Labels: area-ufs, type-bug, needs-response, task-medium
