### ISSUE TITLE
Overwrite in HDFS has sync issue when active sync

### ISSUE THREAD

**Issue by hustnn** [Alluxio/alluxio#9631] opened 2019-08-03 23:40 UTC
**Alluxio Version:**
What version of Alluxio are you using?
2.0 

**Describe the bug**
Seems the old files not delete for overwrite in HDFS when using active sync.

Overwrite should be ``CreateEvent`` with ``Overwrite`` flag, I checked the alluxio sync code, not find the logic uses this flag. How the delete old files are implemented ?

**Comment by yuzhu** [comment] 2019-08-05 18:08
@hustnn Thank you for trying our new features.  Indeed it seems like the `Overwrite` flag in the `CreateEvent` is not respected right now.  There should be a bug fix for this in the next couple of days.

**Comment by hustnn** [comment] 2019-08-19 10:51
@yuzhu Thanks.

**Comment by yuzhu** [comment] 2019-08-20 20:20
@hustnn Could you describe the exact steps you performed to reproduce the error? 
Although we do not handle overwrite specifically, our syncmetadata routine checks for deleted files as well as overwritten files. So in my experiment, when I deleted a file or overwrote a file, the file change got synced to Alluxio as expected.

**Comment by hustnn** [comment] 2019-08-21 08:11
We use using Spark to do the overwrite like `df.write.mode(SaveMode.Overwrite).parquet(path)`

**Comment by yuzhu** [comment] 2019-10-14 21:53
@hustnn 
Sorry it has taken me a while to come back to this issue. Are you still experiencing this issue? 

I tried with `df.write.mode(SaveMode.Overwrite).parquet(path)`, however I was able to see updated Alluxio directory at `path`.  As I understand it, `df.write.mode(SaveMode.Overwrite).parquet(path)` writes one or more parquet files to a specified directory, so it might not overwrite the specific file you had previous generated? If possible, could you paste the exact command or even better a screenshot of what you tried? 

Thanks!

**Comment by hustnn** [comment] 2019-10-15 08:36
@yuzhu Thanks. It is ok. I just use 1.8 after fixing the high load issue https://github.com/Alluxio/alluxio/pull/9977 and periodically sync from outside. 

I think you can try this way:
1. You can upload a file in to a path.
2. Overwrite that path. Then you will find the file in step 1 still exist in Alluxio.

**Comment by LuQQiu** [comment] 2023-01-09 21:37
@yuzhu @tcrain  is this issue still valid?

**Comment by yuzhu** [comment] 2023-01-09 21:49
I didn't repro it at the time.

**Comment by LuQQiu** [comment] 2023-01-09 23:31
Thanks @yuzhu. This issue has been closed due to inactivity and the inability to repro. Please re-open if this still requires investigation.

**Closed by LuQQiu** 2023-01-09 23:31 UTC
Labels: priority-medium, area-core, type-bug, needs-response
