### ISSUE TITLE
Can not remove uncommitted block

### ISSUE THREAD

**Issue by Hollyen** [Alluxio/alluxio#10429] opened 2019-11-07 01:11 UTC
**Alluxio Version:** 
2.0.1

**Describe the bug**
in my test cluster, Disk space is around 100GB, UFS is OBS. 
Because space is limited, so when i use MR to generate 1TB data to alluxio, it fails writing in the middle:
```
2019-11-06 18:11:13,826 WARN [grpc-default-executor-1] alluxio.client.block.stream.GrpcBlockingStream: Received error alluxio.core.client.runtime.io.grpc.StatusRuntimeException: UNKNOWN: Could not find any valid local directory for obs-block-0002- for stream (GrpcDataWriter{request=type: UFS_FALLBACK_BLOCK
id: 49106911232
tier: 0
create_ufs_block_options {
  mount_id: 1
  fallback: false
}
medium_type: ""
pin_on_create: true
, address=WorkerNetAddress{host=node-ana-corevzxf, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=node-ana-coreVzxf, rack=null)}})
2019-11-06 18:11:13,827 WARN [main] alluxio.client.file.FileOutStream: Failed to write into AlluxioStore, canceling write attempt.
alluxio.exception.status.UnknownException: Could not find any valid local directory for obs-block-0002- (GrpcDataWriter{request=type: UFS_FALLBACK_BLOCK
id: 49106911232
tier: 0
create_ufs_block_options {
  mount_id: 1
  fallback: false
}
medium_type: ""
pin_on_create: true
, address=WorkerNetAddress{host=node-ana-corevzxf, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=node-ana-coreVzxf, rack=null)}})
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:154)
	at alluxio.client.block.stream.GrpcBlockingStream.toAlluxioStatusException(GrpcBlockingStream.java:261)
	at alluxio.client.block.stream.GrpcBlockingStream.checkError(GrpcBlockingStream.java:242)
	at alluxio.client.block.stream.GrpcBlockingStream.send(GrpcBlockingStream.java:100)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.sendDataMessage(GrpcDataMessageBlockingStream.java:105)
	at alluxio.client.block.stream.GrpcDataWriter.writeChunk(GrpcDataWriter.java:197)
	at alluxio.client.block.stream.BlockOutStream.updateCurrentChunk(BlockOutStream.java:279)
	at alluxio.client.block.stream.BlockOutStream.write(BlockOutStream.java:158)
	at alluxio.client.file.FileOutStream.writeInternal(FileOutStream.java:257)
	at alluxio.client.file.FileOutStream.write(FileOutStream.java:220)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:58)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at org.apache.hadoop.mapreduce.lib.output.TextOutputFormat$LineRecordWriter.writeObject(TextOutputFormat.java:75)
	at org.apache.hadoop.mapreduce.lib.output.TextOutputFormat$LineRecordWriter.write(TextOutputFormat.java:88)
	at org.apache.hadoop.mapreduce.lib.output.MultipleOutputs.write(MultipleOutputs.java:440)
	at org.notmysock.tpcds.GenTable$DSDGen.map(GenTable.java:211)
	at org.notmysock.tpcds.GenTable$DSDGen.map(GenTable.java:163)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:188)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1840)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:182)
Caused by: alluxio.core.client.runtime.io.grpc.StatusRuntimeException: UNKNOWN: Could not find any valid local directory for obs-block-0002-
	at alluxio.core.client.runtime.io.grpc.Status.asRuntimeException(Status.java:530)
	at alluxio.core.client.runtime.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
	at alluxio.core.client.runtime.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at alluxio.core.client.runtime.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at alluxio.core.client.runtime.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1$1.onClose(GrpcChannel.java:151)
	at alluxio.core.client.runtime.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at alluxio.core.client.runtime.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at alluxio.core.client.runtime.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.core.client.runtime.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at alluxio.core.client.runtime.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at alluxio.core.client.runtime.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.core.client.runtime.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
	at alluxio.core.client.runtime.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at alluxio.core.client.runtime.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at alluxio.core.client.runtime.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.core.client.runtime.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at alluxio.core.client.runtime.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at alluxio.core.client.runtime.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at alluxio.core.client.runtime.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at alluxio.core.client.runtime.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at alluxio.core.client.runtime.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at alluxio.core.client.runtime.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at alluxio.core.client.runtime.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

After that, i check AlluxioWorker log, it keep printing below logs:
```
2019-11-06 22:44:20,462 WARN  AsyncBlockRemover - block-removal-service-7: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:21,466 WARN  AsyncBlockRemover - block-removal-service-3: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:22,465 WARN  AsyncBlockRemover - block-removal-service-1: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:23,469 WARN  AsyncBlockRemover - block-removal-service-5: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:24,463 WARN  AsyncBlockRemover - block-removal-service-9: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:25,478 WARN  AsyncBlockRemover - block-removal-service-8: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:26,465 WARN  AsyncBlockRemover - block-removal-service-0: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:27,470 WARN  AsyncBlockRemover - block-removal-service-4: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:28,464 WARN  AsyncBlockRemover - block-removal-service-6: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:29,469 WARN  AsyncBlockRemover - block-removal-service-2: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:30,476 WARN  AsyncBlockRemover - block-removal-service-7: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:31,481 WARN  AsyncBlockRemover - block-removal-service-3: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:32,473 WARN  AsyncBlockRemover - block-removal-service-1: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:33,472 WARN  AsyncBlockRemover - block-removal-service-5: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:34,470 WARN  AsyncBlockRemover - block-removal-service-9: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:35,469 WARN  AsyncBlockRemover - block-removal-service-1: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:36,473 WARN  AsyncBlockRemover - block-removal-service-0: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:37,474 WARN  AsyncBlockRemover - block-removal-service-4: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:38,476 WARN  AsyncBlockRemover - block-removal-service-6: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:39,474 WARN  AsyncBlockRemover - block-removal-service-8: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:40,475 WARN  AsyncBlockRemover - block-removal-service-7: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:41,480 WARN  AsyncBlockRemover - block-removal-service-3: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:42,490 WARN  AsyncBlockRemover - block-removal-service-8: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:43,482 WARN  AsyncBlockRemover - block-removal-service-5: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:44,479 WARN  AsyncBlockRemover - block-removal-service-9: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:45,504 WARN  AsyncBlockRemover - block-removal-service-1: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:46,485 WARN  AsyncBlockRemover - block-removal-service-8: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:47,487 WARN  AsyncBlockRemover - block-removal-service-4: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:48,493 WARN  AsyncBlockRemover - block-removal-service-6: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
2019-11-06 22:44:49,488 WARN  AsyncBlockRemover - block-removal-service-0: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
```

**To Reproduce**

1. Use OBS or S3 as UFS, and enable writing the data to local disk first.
2. generate large data to alluxio, and alluxio space quota is not enough for all the data.

**Expected behavior**
uncommitted block can be removed, Alluxio worker should not keep deleting the uncommitted block.

**Urgency**
Normal

**Additional context**
Both OBS writing and AlluxioWorker need local disk spaces, there is chance to exausted the space.

**Comment by madanadit** [comment] 2020-01-17 18:03
Potentially a duplicate of https://github.com/Alluxio/alluxio/issues/10519

**Comment by ggezer** [comment] 2021-07-06 17:04
@Hollyen Could you please clarify how did you achieve `enable writing the data to local disk first.` ?
Also, what is your write-type?

From the exception it looks like, you might be using ASYNC_THROUGH since I see `pin_on_create: true`. With this write type, new blocks won't be freed until they're written to UFS. This is to prevent data loss in ASYNC_THROUGH write scheme. So new writes might not find free space and you'd get a exception like you observe.

**Comment by qian0817** [comment] 2021-07-07 01:54
@ggezer We had a similar problem and the configuration we are currently using is
```
alluxio.user.file.readtype.default=CACHE
alluxio.user.file.writetype.default=CACHE_THROUGH
```
In addition to this, there are also a large number of errors reported in the logs.
```
2021-07-07 09:26:48,214 WARN  BlockTransferExecutor - Transfer-order: BlockTransferInfo{TransferType=SWAP, SrcBlockId=91292012904453, DstBlockId=60348149268480, SrcLocation=BlockStoreLocati
on{TierAlias=MEM, DirIndex=0, MediumType=MEM}, DstLocation=BlockStoreLocation{TierAlias=SSD, DirIndex=0, MediumType=SSD}} failed. {}.
alluxio.exception.WorkerOutOfSpaceException: Failed to find space in BlockStoreLocation{TierAlias=SSD, DirIndex=0, MediumType=SSD} to move blockId 91292012904453
        at alluxio.worker.block.TieredBlockStore.moveBlock(TieredBlockStore.java:365)
        at alluxio.worker.block.TieredBlockStore.moveBlock(TieredBlockStore.java:342)
        at alluxio.worker.block.management.BlockTransferExecutor.executeTransferPartition(BlockTransferExecutor.java:136)
        at alluxio.worker.block.management.BlockTransferExecutor.lambda$executeTransferList$0(BlockTransferExecutor.java:97)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-07-07 09:26:48,214 WARN  AlignTask - Insufficient space for worker swap space, swap restore task called.
```
It looks like this error was generated when moving block through the different levels.

**Comment by ggezer** [comment] 2021-07-07 04:28
Moving between tiers will fail the same since there are no space available for allocation as well.

Since your write type is not ASYNC_WRITE, I believe we need to understand why writes are going with `pin_on_create: true` in options. Can you check if you have pinning setting enabled for new files?

**Comment by qian0817** [comment] 2021-07-07 06:13
@ggezer 
We did not change the relevant configuration.
Now I can't find the previous log to determine if it exists `pin_on_create: true` in the first place as this issue. But logs like 
```
2019-11-06 22:44:40,475 WARN  AsyncBlockRemover - block-removal-service-7: invalid block state for block 44124078080, exception is Cannot remove uncommitted blockId 44124078080.
```
still exist until now.

**Comment by ggezer** [comment] 2021-07-08 18:47
@qian0817 The logs you shared are many days apart and are not consistent in their `pin_on_create` setting. So it seems we're looking at different issues here. Please share complete logs along with configuration and the test description for us to be able to look at it.

**Comment by qian0817** [comment] 2021-07-09 02:27
The log where the isssue originally appeared is here.
[worker.log](https://github.com/Alluxio/alluxio/files/6788266/worker.log)
and my configuration is 
```
alluxio.master.hostname=hostname
alluxio.master.mount.table.root.ufs=s3://test/
alluxio.master.mount.table.root.option.aws.accessKeyId=xxx
alluxio.master.mount.table.root.option.aws.secretKey=xxx
alluxio.security.authentication.type=SIMPLE
alluxio.security.authorization.permission.supergroup=hadoop
alluxio.security.authorization.permission.umask=027
alluxio.worker.tieredstore.levels=2
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk
alluxio.worker.tieredstore.level0.dirs.quota=15GB
alluxio.worker.tieredstore.level1.alias=SSD
alluxio.worker.tieredstore.level1.dirs.path=/mnt/ssd/0/alluxio
alluxio.worker.tieredstore.level1.dirs.quota=100GB
alluxio.user.file.readtype.default=CACHE
alluxio.user.file.writetype.default=CACHE_THROUGH
alluxio.underfs.s3.inherit.acl=false
alluxio.underfs.s3.default.mode=0751
alluxio.underfs.allow.set.owner.failure=true
alluxio.integration.worker.resource.cpu=4
alluxio.integration.worker.resource.mem=4096MB
alluxio.user.file.metadata.load.type=ONCE
alluxio.master.metastore=ROCKS
alluxio.master.daily.backup.enabled=true
alluxio.master.daily.backup.time=12:00
alluxio.master.audit.logging.enabled=true
```

**Comment by ggezer** [comment] 2021-07-09 17:19
At this point It's not clear why blocks are not selected for eviction/transfer. 
Can you add below line to worker's log4j file and try to get a repro?

log4j.logger.alluxio.worker.block.BlockMetadataEvictorView=DEBUG

**Comment by qian0817** [comment] 2021-07-10 05:33
@ggezer 
I can't restart it easily because it's an online environment. but i find
```
2021-07-03 01:50:33,449 WARN  BlockTransferExecutor - Transfer-order: BlockTransferInfo{TransferType=SWAP, SrcBlockId=71874868412419, DstBlockId=90027614797842, SrcLocation=BlockStoreLocation{TierAlias=MEM, DirIndex=0, MediumType=MEM}, DstLocation=BlockStoreLocation{TierAlias=SSD, DirIndex=0, MediumType=SSD}} failed. {}. 
java.nio.file.FileSystemException: /mnt/ssd/0/alluxio/alluxioworker/90027614797842 -> /mnt/ramdisk/alluxioworker/90027614797842: No space left on device
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:253)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:471)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at alluxio.util.io.FileUtils.move(FileUtils.java:207)
	at alluxio.worker.block.TieredBlockStore.moveBlockInternal(TieredBlockStore.java:904)
	at alluxio.worker.block.TieredBlockStore.moveBlock(TieredBlockStore.java:352)
	at alluxio.worker.block.TieredBlockStore.moveBlock(TieredBlockStore.java:342)
	at alluxio.worker.block.management.BlockTransferExecutor.executeTransferPartition(BlockTransferExecutor.java:141)
	at alluxio.worker.block.management.BlockTransferExecutor.lambda$executeTransferList$0(BlockTransferExecutor.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
I think [there](https://github.com/Alluxio/alluxio/blob/55cc3b70278672ca0768634c9d1439350faa7cf5/core/server/worker/src/main/java/alluxio/worker/block/management/BlockTransferExecutor.java#L141) is a concurrency exception.

**Comment by ggezer** [comment] 2021-07-14 22:21
@qian0817 At peak capacity, it's possible swaps will fail. Then swap-restore task will activate and will defragment tier spaces. However, in your case swap-restore task is also failing due to bug I just fixed. However, It's still unknown why all your blocks are locked in.

If you can't restart your environment, you can still use Alluxio's `setLogLevel` command to enable these logs on workers.
https://docs.alluxio.io/ee/user/stable/en/operation/Basic-Logging.html#modifying-server-logging-at-runtime

**Comment by ggezer** [comment] 2021-07-14 22:23
```
$ ./bin/alluxio logLevel --logName=alluxio.worker.block.BlockMetadataEvictorView --target=workers --level=DEBUG
$ ./bin/alluxio logLevel --logName=alluxio.worker.block.TieredBlockStore --target=workers --level=DEBUG
$ ./bin/alluxio logLevel --logName=alluxio.worker.block.management.tier.SwapRestoreTask --target=workers --level=DEBUG
```

**Comment by jja725** [comment] 2023-01-26 20:50
Will close it for now, feel free to reopen it and contact us if this is a strong request.

**Closed by jja725** 2023-01-26 20:50 UTC
Labels: priority-high, type-bug
