### ISSUE TITLE
Block XXX   is expected to be XXX  bytes, but only XXX bytes are available. 

### ISSUE THREAD

**Issue by witgo** [Alluxio/alluxio#9151] opened 2019-05-28 13:33 UTC
**Alluxio Version:**
1.8.1

**Describe the bug**
Errors in reading alluxio cache files are as follows
```
Block 278143139053568 is expected to be 25971804 bytes, but only 25971796 bytes are available. Please ensure its metadata is consistent between Alluxio and UFS.
```

**To Reproduce**
I don't know how to reproduce it.

**Expected behavior**
NA

**Urgency**

NA

**Additional context**
NA

**Comment by bf8086** [comment] 2019-05-29 18:32
@witgo Can you maybe describe what is your cluster configuration? What is your under file system and what was the compute task you ran that result in this error?

**Comment by witgo** [comment] 2019-06-04 12:01
@bf8086  

 TPC-H on SparkSQL (4 node(64 vcore 512G MEM).    

````
alluxio.underfs.address=s3a://XX/XX
alluxio.worker.memory.size=128G
alluxio.worker.tieredstore.levels=2
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/opt/data1/alluxio/ramdisk
alluxio.worker.tieredstore.level0.dirs.quota=128G
alluxio.worker.tieredstore.level1.alias=SSD
alluxio.worker.tieredstore.level1.dirs.path=/opt/data2
alluxio.worker.tieredstore.level1.dirs.quota=256G
alluxio.worker.data.folder.permissions=rwxrwx---
alluxio.worker.ufs.instream.cache.enabled=false
alluxio.worker.ufs.instream.cache.max.size=64
alluxio.worker.data.server.domain.socket.address=/opt/data1/alluxio
alluxio.worker.data.server.domain.socket.as.uuid=true

# User properties
alluxio.user.short.circuit.enabled=true
alluxio.user.metrics.collection.enabled=false
alluxio.user.network.netty.writer.close.timeout=10min
alluxio.user.network.socket.timeout=10min
alluxio.user.block.master.client.threads=5
alluxio.user.file.master.client.threads=5
alluxio.user.file.delete.unchecked=true
alluxio.user.file.metadata.load.type=Always
alluxio.user.file.metadata.sync.interval=-1
alluxio.user.file.readtype.default=CACHE
alluxio.user.file.writetype.default=CACHE_THROUGH
alluxio.user.file.write.tier.default=0
```

**Comment by bf8086** [comment] 2019-06-05 01:21
@witgo Thanks! I have a couple questions to understand your scenario better:

Which version of Alluxio are you running?

Does the error happen during the data generation stage or when you are running a query?

Was the data generated directly on S3 or through Alluxio?

**Comment by witgo** [comment] 2019-06-05 02:12
@bf8086  This error occurred during in a query. the data generated through Alluxio.

**Comment by bf8086** [comment] 2019-06-07 04:33
@witgo This might be due to file size inconsistency between Alluxio and UFS. Does it still repro on your cluster? If so, can you free the data from Alluxio storage (assuming you already write all data to S3) and reload them (or just rerun the query and let the query read load the data automatically). Would you still see the error after the cache refresh?

I will check with the team to see if this is a known issue in 1.8.

**Comment by witgo** [comment] 2019-06-07 05:54
@bf8086 After the cache refresh, the error no longer appears.

**Comment by bf8086** [comment] 2019-06-10 20:30
Glad to hear it no longer show up after the refresh.
Unfortunately we were not able to reproduce this issue on our end. Please let us know if you see this error again or find a way to reproduce it consistently, so we can investigate the root cause.

**Comment by rastogiasr** [comment] 2019-07-02 01:44
@witgo  - closing the issue, please reopen if you have a way to reproduce it.

**Closed by rastogiasr** 2019-07-02 01:44 UTC
Labels: type-bug

**Comment by witgo** [comment] 2019-07-11 22:19
@r7raul1984  @bf8086   I have encountered this bug again, and there is no error log output..

**Comment by witgo** [comment] 2019-07-16 01:30
ping @rastogiasr  This issue does not seem to be reopened.

**Comment by witgo** [comment] 2019-07-17 14:29
ping

**Comment by bf8086** [comment] 2019-07-17 16:40
@witgo Can you explain a little bit how you repro'ed it this time? Are you running a query? Is your data accessed outside of Alluxio? Were there any warning or unusual log entries before the issue happened?

**Comment by witgo** [comment] 2019-07-18 02:45
Once this problem arises, it causes Spark SQL to misreport any sql job that reads to this file. Data is not accessible outside of alluxio. The data files of the underlying hdfs are not a problem.
The logs that appear frequently are as follows:

```
java.net.SocketException: Socket closed
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
        at org.apache.thrift.transport.TIOStreamTransport.close(TIOStreamTransport.java:110)
        at org.apache.thrift.transport.TSocket.close(TSocket.java:235)
        at org.apache.thrift.transport.TSaslTransport.close(TSaslTransport.java:402)
        at org.apache.thrift.transport.TSaslClientTransport.close(TSaslClientTransport.java:37)
        at alluxio.AbstractClient.disconnect(AbstractClient.java:335)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:440)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:389)
        at alluxio.worker.block.BlockMasterClient.commitBlock(BlockMasterClient.java:87)
        at alluxio.worker.block.DefaultBlockWorker.commitBlock(DefaultBlockWorker.java:314)
        at alluxio.worker.netty.BlockWriteHandler$BlockPacketWriter.completeRequest(BlockWriteHandler.java:131)
        at alluxio.worker.netty.BlockWriteHandler$BlockPacketWriter.completeRequest(BlockWriteHandler.java:109)
        at alluxio.worker.netty.AbstractWriteHandler$PacketWriter.runInternal(AbstractWriteHandler.java:318)
        at alluxio.worker.netty.AbstractWriteHandler$PacketWriter.run(AbstractWriteHandler.java:250)
        at alluxio.worker.netty.BlockWriteHandler$BlockPacketWriter.run(BlockWriteHandler.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by bf8086** [comment] 2019-07-18 22:16
Thanks for the logs. I have a couple questions:

- Does it happen if you delete and regenerate the data then rerun the benchmark?
- Are you seeing it with S3 as underfs or HDFS or both?
- Can you provide a list of steps with commands or queries you ran to generate test data and run the benchmark?

**Comment by witgo** [comment] 2019-07-19 00:57
1. The production system has multiple jobs running and is not sure how much time to trigger this log.
2. yes
3. insert into table , select table, performed once an hour.

**Comment by bf8086** [comment] 2019-07-19 21:47
Does it repro every time after you generate the data or only sometimes?

For the block size mismatch exception, do you know which file it was trying to read when the error occurred? If you do, can you run `alluxio fs stat <file_name>` and post the output here?

For the SocketException, can you check Alluxio master log to see if there is any error at the corresponding time?

**Comment by witgo** [comment] 2019-07-21 08:42
1. Only sometimes.
2.  The cached data has been cleaned up and only appeared twice, it seems that the last 8 bytes of data are lost.
3. No other related errors.

**Comment by samloyal** [comment] 2021-10-15 06:56
same issue
free alluxio and reload it happen always

alluxio : 2.6.2
ufs: s3
