### ISSUE TITLE
Worker memory leaks when submit to the block writer thread pool are rejected

### ISSUE THREAD

**Issue by qian0817** [Alluxio/alluxio#16528] opened 2022-11-10 12:25 UTC
**Alluxio Version:**
2.7.3

**Describe the bug**
Take a write request as an example.
If the `mSerializingExecutor` is full and throw a `RejectedExecutionException`, the buffer will not release and cause memory leak.
![image](https://user-images.githubusercontent.com/45898769/201089824-e33f813f-5a9c-4a91-9127-83ec7504f6e0.png)

If the `mSerializingExecutor` is full and throw a `RejectedExecutionException`, the request will not cancel and some resources such as UFS write stream will not be close.
![image](https://user-images.githubusercontent.com/45898769/201090123-6d67422f-a063-4ce5-95ea-13893b9fbd00.png)

**To Reproduce**
RejectedExecutionException occurs when requesting the same Worker at the same time with high pressure.

**Expected behavior**
These resources should be released correctly.

**Urgency**
High

**Are you planning to fix it**

**Additional context**

**Comment by HelloHorizon** [comment] 2022-11-17 00:58
@yuzhu can you take a look?

**Comment by HelloHorizon** [comment] 2022-11-18 00:40
@dbw9580 do you think this one relates to #16512 ?

**Comment by dbw9580** [comment] 2022-11-21 05:18
Seems https://github.com/Alluxio/alluxio/pull/11310 fixed the problem on the read path, but on the write path the same problem is still there. Will take a closer look into the write path to make sure a similar fix can solve this issue.

https://github.com/Alluxio/alluxio/pull/16512 tries to address the general case where a buffer is left unreleased. I don't think #16512 can be a direct fix for this particular issue, tho.

**Comment by LuQQiu** [comment] 2023-01-03 17:47
@dbw9580 any update on this issue?

**Comment by HelloHorizon** [comment] 2023-03-03 21:55
@dbw9580 any update on this pr?

**Comment by Xenorith** [comment] 2023-05-16 00:44
the issue is related to block store which is not relevant in 3.x, so we are not aiming to fix this

**Closed by Xenorith** 2023-05-16 00:44 UTC
Labels: priority-high, type-bug, area-worker
