### ISSUE TITLE
Alluxio not fetching file permissions from fine-grained GCS bucket acls.

### ISSUE THREAD

**Issue by hamzabll5858** [Alluxio/alluxio#11291] opened 2020-04-14 05:53 UTC
**Alluxio Version:2.2.0**

**Description**
My bucket-level access control is set to fine-grained in GCS. When I upload a file into the GCS bucket. Alluxio is not fetching the acl attached to files. It is also not assigning alluxio.underfs.gcs.default.mode=0775 that I have set in alluxio-site.properties. According to [link](https://docs.alluxio.io/os/user/stable/en/reference/Properties-List.html) alluxio.underfs.gcs.default.mode should be applied to file if permissions are not discovered.

**To Reproduce**

- Run Alluxio cluster as docker containers. Change the parameters according to your setup
**Master**
docker run -d  --rm \
    -p 19999:19999 \
    -p 19998:19998 \
    -p 39999:39999 \
    --net=alluxio_network \
    --name=alluxio-master \
    -v /data/master:/opt/alluxio-2.2.0/logs \
    -v /data/alluxio_ufs:/opt/alluxio/underFSStorage \
    -e ALLUXIO_JAVA_OPTS="-Dalluxio.master.hostname=alluxio-master -Dalluxio.master.mount.table.root.ufs=gs://bucket/global -Dalluxio.user.file.delete.unchecked=true -Dalluxio.user.file.writetype.default=CACHE_THROUGH -Dalluxio.user.file.ufs.tier.enabled=true -Dalluxio.security.authorization.permission.umask=002 -Dalluxio.master.mount.table.root.ufs=gs://bucket/global -Dalluxio.master.mount.table.root.option.fs.gcs.accessKeyId=****** -Dalluxio.master.mount.table.root.option.fs.gcs.secretAccessKey=****** -Dalluxio.underfs.gcs.default.mode=0775"  \
    alluxio/alluxio master
**Worker**
docker run -d --rm \
    -p 29999:29999 \
    -p 29998:29998 \
    -p 30000:30000 \
    --net=alluxio_network \
    --name=alluxio-worker-1 \
    -v /data/worker:/opt/alluxio-2.2.0/logs \
    -v /data/alluxio_ufs:/opt/alluxio/underFSStorage \
    --shm-size=16G \
    -e ALLUXIO_JAVA_OPTS="-Dalluxio.worker.memory.size=16G  -Dalluxio.master.hostname=alluxio-master  -Dalluxio.worker.hostname=192.168.3.91 -Dalluxio.user.file.delete.unchecked=true -Dalluxio.user.file.writetype.default=CACHE_THROUGH -Dalluxio.user.file.ufs.tier.enabled=true -Dalluxio.security.authorization.permission.umask=002 -Dalluxio.master.mount.table.root.ufs=gs://bucket/global -Dalluxio.master.mount.table.root.option.fs.gcs.accessKeyId=****** -Dalluxio.master.mount.table.root.option.fs.gcs.secretAccessKey=****** -Dalluxio.underfs.gcs.default.mode=0775"  \
    alluxio/alluxio worker

- Create a bucket in GCS with fine-grained permission.
- Upload a file in GCS bucket and see its permission in Alluxio

**Expected behavior**
If alluxio is not supporting fine-grained permission. It should at least assign a default permission to the files from alluxio.underfs.gcs.default.mode parameter

**Urgency**
Blocked. Need to assign permission to individual files in alluxio

**Additional context**
![Screenshot from 2020-04-14 10-46-47](https://user-images.githubusercontent.com/16019303/79190444-cc111d80-7e3d-11ea-9f2e-3d6311661bf2.png)
![Screenshot from 2020-04-14 10-46-53](https://user-images.githubusercontent.com/16019303/79190447-d03d3b00-7e3d-11ea-84cc-1f78427fd1ff.png)

**Comment by apc999** [comment] 2020-04-20 06:37
close this ticket as we could not reproduce this issue @hamzabll5858 .
Feel free to reopen it once you encounter this again

**Closed by apc999** 2020-04-20 06:37 UTC
Labels: type-bug
