### ISSUE TITLE
Raft took too long to transfer leadership

### ISSUE THREAD

**Issue by jayzhenghan** [Alluxio/alluxio#14563] opened 2021-11-22 10:05 UTC
When Alluxio is in production with 10millions of files and a large amount of metadata operations, master leadership takes a long time (longer than minutes). We took a look at the code and find the following code
<img width="1100" alt="wecom-temp-acfb99df55ed7b7176b82302385f7b46" src="https://user-images.githubusercontent.com/68948288/142841958-a0847a1c-615e-40fa-a2c3-b6312cf09b3f.png">
There is a default 20s waiting time, what's the usage of this code? what happens if it is removed?

**Comment by jayzhenghan** [comment] 2021-11-22 11:51
@jenoudet @ggezer @yuzhu

**Comment by yuzhu** [comment] 2021-11-22 20:56
@jenoudet I think @jayzhenghan is curious why there is a delay in this process.  so feel free to explain here. because they are noticing long raft failovers.

**Comment by jenoudet** [comment] 2021-11-22 23:34
This waiting timeout is to ensure a smoother leader transition. By waiting this amount, we ensure that every member of the quorum has taken into account who the new leader is, and we can start processing new entries or catching up older ones from others in the quorum with this certainty in mind.

**Comment by kevincai** [comment] 2021-11-24 09:38
In practical, this wait is not necessary, if there are network split, wait this longer may not help anyway.

We have a private patch for this, as long as the following condition satisfied, leader can serve the requests.

```
@@ -706,9 +706,15 @@ public class RaftJournalSystem extends AbstractJournalSystem {
 
       // Wait election timeout so that this master and other masters have time to realize they
       // are not leader.
-      CommonUtils.sleepMs(mConf.getMaxElectionTimeoutMs());
-      if (stateMachine.getLastAppliedSequenceNumber() != lastAppliedSN
-          || stateMachine.getLastPrimaryStartSequenceNumber() != gainPrimacySN) {
+      try {
+        CommonUtils.waitFor("check primacySN " + gainPrimacySN + " and lastAppliedSN "
+            + lastAppliedSN + " to be applied to leader", () ->
+            stateMachine.getLastAppliedSequenceNumber() == lastAppliedSN
+                && stateMachine.getLastPrimaryStartSequenceNumber() == gainPrimacySN,
+            WaitForOptions.defaults()
+                .setInterval(Constants.SECOND_MS)
+                .setTimeoutMs((int) mConf.getMaxElectionTimeoutMs()));
+      } catch (TimeoutException e) {
         // Someone has committed a journal entry since we started trying to catch up.
         // Restart the catchup process.
         continue;
```

**Comment by jayzhenghan** [comment] 2021-11-24 11:24
@kevincai I agree with you，thanks～

**Comment by qian0817** [comment] 2021-11-24 16:07
I have also paid attention to this code before, and I'd like to explain my point of view. Imagine that there are three raft nodes A, B, C. At beginning A is the leader node, then A and the other two nodes are disconnected from each other because of network split, then B becomes the new leader, but at this time A does't realize that it is not the leader any more, and A and B RPC port will be opened and accept the service at the same time. At this time, A will still accept requests from the client, and if it encounters a modification request, it will first successfully modify the UFS but fail to write the raft log, thus causing inconsistencies between the metadata in aluxio and ufs. According to my understanding of ratis, Ratis implements leader step down, A will become a follower node because it does not successfully heartbeat most of the nodes in its cluster in an election, thus close it's rpc server. So in my opinion, waiting for an election timeout seems to be necessary.

For how to reducing the raft switching leader time, in this version you are using there should be a long time consumed in starting the WEB server, I suggest to merge this [PR](https://github.com/Alluxio/alluxio/pull/13781) firstly, in my previous tests I found that I can reduce the switching time by about 15s.

Then I suggested to reduce the election timeout of raft according to the deployment conditions of masters, and we referred to [the advice given by etcd](https://etcd.io/docs/v3.4/tuning/#time-parameters) when setting the parameters.

**Comment by LuQQiu** [comment] 2021-11-24 23:03
@yuzhu @jenoudet 
@kevincai 's code suggestions looks good to me, how about making that change?
Or we can have another propertykey to provide optional waiting time when leader transfers

**Comment by kevincai** [comment] 2021-11-25 07:33
@qian0817 

I agree with your point on causing UFS and raft log inconsistency. But seems the situation you described could happen in any stage during the system running, why particularly needs a time wait during the new leader start? The sleep during startup can prevent the new leader from losing its primacy too soon, but can't prevent a long running leader suddenly lost its primacy, and can still causes data inconsistency.

Alluxio can follow etcd's timeout principal, but can't follow its timeout value, JVM STW FGC will be a big trouble when elect timeout is set to < 5s.

**Comment by kevincai** [comment] 2021-11-25 07:36
> @yuzhu @jenoudet @kevincai 's code suggestions looks good to me, how about making that change? Or we can have another propertykey to provide optional waiting time when leader transfers

I prefer the patch to be private for now, until the impact to data integrity is fully discussed get to a conclusion. In our case, we use UFS mostly as READ-ONLY source, so underlying UFS modification is not a concern, the risk is acceptable and taken.

**Comment by qian0817** [comment] 2021-11-25 13:23
To be honest, I think the current implementation should have inconsistent issue between UFS and alluxio metadata when the leader is down, but I haven't tried to reproduce it yet.
@jenoudet Can you explain in more detail the reasons for the wait and whether it is because there are issues that I have not considered.

**Comment by yuzhu** [comment] 2021-12-01 19:54
@kevincai @qian0817 we had an internal discussion and think that @kevincai 's private patch should  at least be no worse than the current delay. As for the inconsistent issue, @qian0817 i don't see how a longer delay would help in the case of network partition? could you explain more?  If no objections, we will welcome a patch from @kevincai or we can make a PR similar to kevin's suggestion, whichever you prefer.

**Comment by qian0817** [comment] 2021-12-02 15:40
@yuzhu
If network partitioning happens, then the previous leader node will definitely become a follower node after one election timeout, and will not cause two nodes to regard itself as a leader node at the same time.
At the same time, I do not oppose this modification, because the current implementation when the leader is down is also inconsistent situation.

**Comment by jayzhenghan** [comment] 2021-12-05 08:41
![image](https://user-images.githubusercontent.com/68948288/144739673-b3e2a77a-1569-4cdc-9f28-a5b3bdd66ec4.png)
106 is leader，Why would 106 vote for 105?, Make 105 successful

**Comment by jenoudet** [comment] 2021-12-06 19:32
To answer your first question: 105 would start a new election if it does not receive a heartbeat from the leader for a period of time. When a member starts a new election, it votes for itself and requests votes from all the other members of the quorum. The other members accept this request vote by default (there are some rejection conditions, such as if another member is itself running another election).

**Comment by jayzhenghan** [comment] 2021-12-08 08:02
> To answer your first question: 105 would start a new election if it does not receive a heartbeat from the leader for a period of time. When a member starts a new election, it votes for itself and requests votes from all the other members of the quorum. The other members accept this request vote by default (there are some rejection conditions, such as if another member is itself running another election).

![image](https://user-images.githubusercontent.com/68948288/145171013-eaf97fcd-8c09-4d5f-b244-f18dae4e1be2.png)
What is the reason for this switch? I found out that in the ping-pong selection

**Comment by jayzhenghan** [comment] 2021-12-08 14:18
> To answer your first question: 105 would start a new election if it does not receive a heartbeat from the leader for a period of time. When a member starts a new election, it votes for itself and requests votes from all the other members of the quorum. The other members accept this request vote by default (there are some rejection conditions, such as if another member is itself running another election).

![image](https://user-images.githubusercontent.com/68948288/145223726-55f5aa8b-e130-4db1-970c-8913d9d89501.png)
Error sending snapshot to leader
@jenoudet

**Comment by ggezer** [comment] 2021-12-09 18:54
This wait was most probably added because we were using copycat, where leadership stability was not managed as comprehensively as in ratis. So I can't provide any counter argument to make the wait before checking the state. 

I think we can go ahead with the fix provided; https://github.com/Alluxio/alluxio/issues/14563#issuecomment-977701877

**Comment by jenoudet** [comment] 2021-12-09 18:56
PR #14612 implements these changes @ggezer.

**Closed** 2021-12-09 23:37 UTC
Labels: priority-high, area-core, type-debt
