### ISSUE TITLE
failed to load jar /opt/alluxio-2.9.3/lib/alluxio-underfs-hadoop-cosn-3.1.0-5.8.5-2.9.3.jar NoClassdDefFoundError :alluxio/underfs/hdfs/HdfsUnderFileSystemFactory

### ISSUE THREAD

**Issue by morpheusyu** [Alluxio/alluxio#17554] opened 2023-06-05 06:52 UTC
my presto is deployed in docker individually,alluxio is deployed in another docker container  individually,
alluxio can start well,when presto query hive table ,I can get the query result ,I try to turn on the short circuit read but failed becaues web ui indicater BytesReadLocalThroughput is always 0 no matter how i query,and the alluxio worker log report below  error 
      failed to load jar /opt/alluxio-2.9.3/lib/alluxio-underfs-hadoop-cosn-3.1.0-5.8.5-2.9.3.jar NoClassdDefFoundError :alluxio/underfs/hdfs/HdfsUnderFileSystemFactory
      I think my failing turning  on short circuit read  maybe have something with above error ,can u give me some advice

![Uploading 51685944317_.pic_hd.jpg…]()
![Uploading 51685944317_.pic_hd.jpg…]()

**Comment by dbw9580** [comment] 2023-06-07 13:17
duplicate of #17554

**Closed by dbw9580** 2023-06-07 13:17 UTC
