### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Invalid property key ALLUXIO_CLIENT_HOSTNAME

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#11802] opened 2020-07-22 04:27 UTC
**Alluxio Version:**
2.3.0-SNAPSHOT

**Describe the bug**

Due to https://github.com/Alluxio/alluxio/blob/01d1a9adb5979936b4f9e3beaaa5a7cf8bc9b656/integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml#L98

```
          env:
          - name: ALLUXIO_CLIENT_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: ALLUXIO_CLIENT_JAVA_OPTS
            value: " -Dalluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME} "
          {{- range $key, $value := .Values.fuse.env }}
```

`ALLUXIO_CLIENT_HOSTNAME` is passed to Alluxio runtime and triggers RuntimeException when resolving `alluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME}`:

```
Starting alluxio-fuse on local host.
Exception in thread "main" java.lang.RuntimeException: Invalid property key ALLUXIO_CLIENT_HOSTNAME
         at alluxio.conf.InstancedConfiguration.lookupRecursively(InstancedConfiguration.java:457)
         at alluxio.conf.InstancedConfiguration.lookup(InstancedConfiguration.java:430)
         at alluxio.conf.InstancedConfiguration.isResolvable(InstancedConfiguration.java:168)
         at alluxio.conf.InstancedConfiguration.isSet(InstancedConfiguration.java:177)
         at alluxio.util.network.NetworkAddressUtils.getLocalNodeName(NetworkAddressUtils.java:387)
         at alluxio.network.TieredIdentityFactory.create(TieredIdentityFactory.java:98)
         at alluxio.network.TieredIdentityFactory.localIdentity(TieredIdentityFactory.java:62)
         at alluxio.client.block.AlluxioBlockStore.create(AlluxioBlockStore.java:77)
         at alluxio.client.file.BaseFileSystem.<init>(BaseFileSystem.java:106)
         at alluxio.client.file.MetadataCachingBaseFileSystem.<init>(MetadataCachingBaseFileSystem.java:56)
         at alluxio.client.file.FileSystem$Factory.create(FileSystem.java:144)
         at alluxio.client.file.FileSystem$Factory.create(FileSystem.java:117)
         at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:96)
```

**To Reproduce**
Using Helmchart as daemonset

**Expected behavior**

**Urgency**

**Additional context**

**Comment by jiacheliu3** [comment] 2020-08-10 14:08
Fixed by https://github.com/Alluxio/alluxio/pull/11840

**Comment by jiacheliu3** [comment] 2020-08-12 13:43
The issue is resolved in 
1. Alluxio 2.3.0 release, by putting `alluxio.user.hostname` into `ALLUXIO_JAVA_OPTS`
2. In 2.4 in https://github.com/Alluxio/alluxio/pull/11971, by fixing how `alluxio.user.hostname` is put into ALLUXIO_FUSE_JAVA_OPTS and correctly exporting it.

**Closed** 2021-09-02 12:58 UTC
Labels: type-bug
