### ISSUE TITLE
[alluxio-2.0.0] worker failed to start when configure dirs.path with multi value 

### ISSUE THREAD

**Issue by FrankYu** [Alluxio/alluxio#9410] opened 2019-07-03 07:30 UTC
**Alluxio Version:**
2.0.0

**Describe the bug**
worker failed to start when config dirs.path with multi value 

**To Reproduce**
config alluxio-site.properties with content as 'Additional context', then try to run alluxio-start.sh worker on worker nodes 

**Expected behavior**
worker should started successfully 

**Urgency**
high

**Additional context**

alluxio-site.properties of worker as below: 

`# COMMON configurations
alluxio.debug=true
alluxio.fuse.cached.paths.max=5000
alluxio.fuse.debug.enabled=true
alluxio.fuse.user.group.translation.enabled=true
alluxio.home=/usr/local/alluxio/
alluxio.job.master.client.threads=4096
alluxio.job.master.job.capacity=10000000
alluxio.job.master.lost.worker.interval=5s
alluxio.job.master.worker.heartbeat.interval=60s
alluxio.job.master.worker.timeout=60s
alluxio.locality.compare.node.ip=true
alluxio.logs.dir=/var/log/alluxio/
alluxio.underfs.hdfs.configuration=/usr/local/alluxio/conf/core-site.xml:/usr/local/alluxio/conf/hdfs-site.xml
alluxio.underfs.hdfs.remote=true
alluxio.underfs.listing.length=10000
alluxio.underfs.object.store.service.threads=200
alluxio.webui.cors.enabled=true
alluxio.zookeeper.address=xxx
alluxio.zookeeper.enabled=true
alluxio.zookeeper.session.timeout=300s
#MASTER configurations
alluxio.master.activesync.interval=60s
alluxio.master.activesync.maxactivity=50
alluxio.master.audit.logging.queue.capacity=1000000
alluxio.master.backup.directory=/mnt/glusterfs-alluxio/alluxio/backup
alluxio.master.daily.backup.enabled=true
alluxio.master.daily.backup.time=01:00
alluxio.master.executor.parallelism=36
alluxio.master.journal.checkpoint.period.entries=20000000
alluxio.master.journal.flush.batch.time=10s
alluxio.master.journal.folder=/mnt/glusterfs-alluxio/alluxio/journal
alluxio.master.journal.log.size.bytes.max=500MB
alluxio.master.journal.type=UFS
alluxio.master.jvm.monitor.enabled=true
alluxio.master.metastore=ROCKS
alluxio.master.metastore.dir=/mnt/nvme
alluxio.master.metastore.inode.cache.evict.batch.size=100000
alluxio.master.metastore.inode.cache.high.water.mark.ratio=0.8
alluxio.master.metastore.inode.cache.low.water.mark.ratio=0.5
alluxio.master.metastore.inode.cache.max.size=100000000
alluxio.master.metastore.inode.enumerator.buffer.count=100000
alluxio.master.mount.table.root.ufs=/mnt/glusterfs-alluxio/alluxio/data/
alluxio.master.periodic.block.integrity.check.interval=1hr
alluxio.master.rpc.executor.max.pool.size=100000
alluxio.master.ufs.block.location.cache.capacity=100000000
alluxio.master.ufs.path.cache.capacity=1000000
alluxio.master.ufs.path.cache.threads=128
alluxio.master.worker.threads.max=51200
alluxio.master.worker.threads.min=2560
# WORKER configurations
alluxio.worker.block.heartbeat.interval=60s
alluxio.worker.block.heartbeat.timeout=2min
alluxio.worker.block.master.client.pool.size=100
alluxio.worker.block.threads.max=4096
alluxio.worker.data.server.domain.socket.address=/usr/local/alluxio/run/
alluxio.worker.data.server.domain.socket.as.uuid=true
alluxio.worker.file.buffer.size=1G
alluxio.worker.filesystem.heartbeat.interval=60s
alluxio.worker.jvm.monitor.enabled=true
alluxio.worker.memory.size=20GB
alluxio.worker.network.async.cache.manager.threads.max=64
alluxio.worker.network.block.reader.threads.max=4096
alluxio.worker.network.flowcontrol.window=16MB
alluxio.worker.network.max.inbound.message.size=16MB
alluxio.worker.network.reader.buffer.size=16MB
alluxio.worker.network.reader.max.chunk.size.bytes=512MB
alluxio.worker.tieredstore.block.lock.readers=4000
alluxio.worker.tieredstore.levels=1
alluxio.worker.tieredstore.level0.alias=SSD
#alluxio.worker.tieredstore.level0.dirs.path=/mnt/ssd1
#alluxio.worker.tieredstore.level0.dirs.quota=745GB
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ssd1,/mnt/ssd2,/mnt/ssd3
alluxio.worker.tieredstore.level0.dirs.quota=745GB,745GB,745GB
alluxio.worker.tieredstore.level0.watermark.high.ratio=0.95
alluxio.worker.tieredstore.level0.watermark.low.ratio=0.5
# USER configurations
alluxio.user.block.master.client.threads=128
alluxio.user.block.remote.read.buffer.size.bytes=1GB
alluxio.user.block.size.bytes.default=128MB
alluxio.user.block.worker.client.pool.size=2048
alluxio.user.file.buffer.bytes=128MB
alluxio.user.file.master.client.threads=128
alluxio.user.file.metadata.load.type=ONCE
alluxio.user.file.metadata.sync.interval=-1
alluxio.user.file.passive.cache.enabled=true
alluxio.user.local.reader.chunk.size.bytes=128MB
alluxio.user.metrics.collection.enabled=true
alluxio.user.network.data.timeout=60s
alluxio.user.network.max.inbound.message.size=1GB
alluxio.user.network.netty.worker.threads=16
alluxio.user.network.reader.buffer.size.messages=64
alluxio.user.network.reader.chunk.size.bytes=128MB
alluxio.user.rpc.retry.base.sleep=5s
alluxio.user.rpc.retry.max.duration=2min
alluxio.user.short.circuit.enabled=true
alluxio.user.ufs.delegation.read.buffer.size.bytes=128MB
# RESOURCE configurations
# SECURITY configurations
alluxio.security.group.mapping.class=alluxio.security.group.provider.ShellBasedUnixGroupsMapping
alluxio.security.login.impersonation.username=_NONE_`

**Comment by FrankYu** [comment] 2019-07-03 08:22
few log found in worker.log 

2019-07-03 16:14:02,403 ERROR ProcessUtils - Uncaught exception while running Alluxio worker, stopping it and exiting. Exception alluxio.exception.status.UnknownException, Root Cause io.grpc.StatusRuntimeException: UNKNOWN
2019-07-03 16:14:11,453 ERROR ProcessUtils - Uncaught exception while stopping Alluxio worker, simply exiting. Exception java.lang.NullPointerException, Root Cause null

**Comment by apc999** [comment] 2019-07-03 17:18
I think this issue is related to https://github.com/Alluxio/alluxio/issues/9279

**Comment by yuzhu** [comment] 2019-08-07 22:57
Hi @FrankYu , I was not able to reproduce this error on my side. Could you try the exact same configuration with `dirs.path` set to a single value? does the same error occur?

**Comment by gpang** [comment] 2019-08-14 14:38
This occurs when the worker is not formatted and has left over blocks when starting. This was fixed by this PR: https://github.com/Alluxio/alluxio/pull/9517

**Comment by gpang** [comment] 2019-08-14 18:34
This is the related issue: #9501

**Closed** 2019-08-14 22:12 UTC
Labels: priority-high, target-2.0.1, target-2.1.0, type-bug
