### ISSUE TITLE
Will writing journal asynchronously result in the loss of the journal log?

### ISSUE THREAD

**Issue by adol001** [Alluxio/alluxio#14813] opened 2022-01-07 10:19 UTC
**Alluxio Version:**
2.7.2

**Describe the bug**
Many journals are written asynchronously to the related journal writer through AsyncJournalWriter. If the journal is in AsyncJournalWriter.mQueue but there is no time to flush to the journal writer before jvm hangs, will the journal be lost?

Because of pre-apply(mInodeTree.updateInode => mState.applyAndJournal), the status is changed, the journal is lost, and the client operation is successful. If the service restarts, did that client operation changed the state?

**Comment by jenoudet** [comment] 2022-01-10 17:59
This question is a duplicate of a question answered on Slack by @LuQQiu. Here was her answer that I agree with:
"Operation is finished and journal is written to local journal before returning success to client. so if jvm hangs, client will take a longer time to receive the operation succeed results because it needs to wait for the journal written."

**Closed by jenoudet** 2022-01-10 17:59 UTC
Labels: type-bug
