### ISSUE TITLE
Alluxio master failed to flush journal entry

### ISSUE THREAD

**Issue by Yang9613** [Alluxio/alluxio#16961] opened 2023-02-28 06:33 UTC
**Alluxio Version:**
2.8.0
**Describe the bug**
Last month we found an alluxio cluster had a large number of requests failed and the master prints the following log

```
2023-01-30 05:48:54,376 WARN  AsyncJournalWriter - Failed to flush journal entry: Timed out after waiting 30000 milliseconds for journal entries to be processed
java.io.IOException: Timed out after waiting 30000 milliseconds for journal entries to be processed
        at alluxio.master.journal.raft.RaftJournalWriter.flush(RaftJournalWriter.java:134)
        at alluxio.master.journal.AsyncJournalWriter.doFlush(AsyncJournalWriter.java:323)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
        at alluxio.master.journal.raft.RaftJournalWriter.flush(RaftJournalWriter.java:123)
        ... 2 more

2023-01-30 05:48:54,392 WARN  AsyncJournalWriter - Failed to flush journal entry: Server coarserankfeaturefile-master-1_20022@group-ABB3109A44C1 is not the leader
org.apache.ratis.protocol.exceptions.NotLeaderException: Server coarserankfeaturefile-master-1_20022@group-ABB3109A44C1 is not the leader
        at org.apache.ratis.server.impl.RaftServerImpl.generateNotLeaderException(RaftServerImpl.java:644)
        at org.apache.ratis.server.impl.RaftServerImpl.checkLeaderState(RaftServerImpl.java:609)
        at org.apache.ratis.server.impl.RaftServerImpl.submitClientRequestAsync(RaftServerImpl.java:737)
        at org.apache.ratis.server.impl.RaftServerProxy.lambda$submitClientRequestAsync$9(RaftServerProxy.java:417)
        at org.apache.ratis.server.impl.RaftServerProxy.lambda$null$7(RaftServerProxy.java:412)
        at org.apache.ratis.util.JavaUtils.callAsUnchecked(JavaUtils.java:115)
        at org.apache.ratis.server.impl.RaftServerProxy.lambda$submitRequest$8(RaftServerProxy.java:412)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at org.apache.ratis.server.impl.RaftServerProxy.submitRequest(RaftServerProxy.java:411)
        at org.apache.ratis.server.impl.RaftServerProxy.submitClientRequestAsync(RaftServerProxy.java:417)
        at alluxio.master.journal.raft.RaftJournalAppender.sendLocalRequest(RaftJournalAppender.java:94)
        at alluxio.master.journal.raft.RaftJournalAppender.sendAsync(RaftJournalAppender.java:77)
        at alluxio.master.journal.raft.RaftJournalWriter.flush(RaftJournalWriter.java:122)
        at alluxio.master.journal.AsyncJournalWriter.doFlush(AsyncJournalWriter.java:323)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

In order to solve this problem quickly, I restart all masters but useless. Finally I clear the meta directory on all masters and reload metadata from ufs, the cluster can reponse these requests as usual.
During solve this problem, I only save the above log, so can’t provide more information

**To Reproduce**
This problem only happened once，I can't reproduce it

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by dbw9580** [comment] 2023-02-28 09:33
@elega for visibility

**Comment by elega** [comment] 2023-02-28 13:00
Hi thanks for reporting the issue.

I noticed this log: 
org.apache.ratis.protocol.exceptions.NotLeaderException: Server coarserankfeaturefile-master-1_20022@group-ABB3109A44C1 is not the leader

Seems like the cluster failover happened before you encountered the issue. When a failover happens, the previous primary master would lost its primacy and a new primary master will be elected. The previous primary master will not be allowed to flush new journals as it has converted to a standby master. 

The reason of failover can be various. For example, if a network partition happened between the primary master and two standby masters, a failover can happen. If primary master is dead, a failover can happen. If primary master is overloaded by excessive requests and fails to respond RAFT heartbeat, a failover can also happen. It's hard to tell based on the information you provided.

When a failover happened, you might get a bunch of errors when your client RPC the master. These clients will disconnect and retry. Once a new primary master is elected, the clients should connect to the new primary master instead and start getting success responses. So probably you just need to be a bit more patient and wait for a longer while. The failover process is not as fast as you thought. Workers need to register to the new master to report it block location and based on your cluster size, this process might take you up to 10-20 minutes. 

The reason why you was still not able to use your cluster normally after you restart is probably also because it takes time for the alluxio masters to
1. apply the previous journals
2. wait for the worker registration.
The cluster will not be in service until these are done.

If possible, i recommend you do some failover drill on staging clusters. You can just kill the primary master and observe how the cluster recovers from a primary master failure.

Thanks a lot!

**Comment by HelloHorizon** [comment] 2023-03-08 23:32
@Yang9613, please reopen this issue if you reencounter this bug, will close it since it's hard to reproduce

**Closed by HelloHorizon** 2023-03-08 23:32 UTC
Labels: priority-high, type-bug, needs-info, area-ha
