### ISSUE TITLE
Dst directory will not be deleted when distributedCp failed

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#13212] opened 2021-04-12 12:32 UTC
**Alluxio Version:**
2.3.1

**Describe the bug**
When `alluxio fs distributedCp` failed, the <dst> directory will not be deleted. If user run `alluxio fs distributedCp` again, it will failed due to <dst> already exist.

**Expected behavior**
When `alluxio fs distributedCp` failed, the <dst> directory will be deleted.

**Urgency**
Normal.

**Comment by LuQQiu** [comment] 2021-04-22 02:56
@JySongWithZhangCe Is this behavior still true with the latest master or latest versions?

**Comment by LuQQiu** [comment] 2021-04-22 03:02
@bradyoo I think for distributedLoad, if a file is loaded in the first distributedLoad, the second time the load is a no-op for this file. Can we do the same thing for distributedCp? When copying a directory, if a file/folder in this directory with the same name exist, we don't cp that file?

maybe a better question for what user experience we want? what's your opinion @calvinjia ?

**Comment by bradyoo** [comment] 2021-04-22 17:16
See https://github.com/Alluxio/alluxio/pull/13262. The behavior is changing so that distributedCp will actually overwrite the files because that was the intended behavior when it was first implemented. 

We are definitely not doing the behavior where when distributedCp fails, directory getting deleted. That is because there are cases when some files are not properly completed or intermittent problems with some mounts, etc and in those cases, many users have desired that not all of the copy to fail.

The no-op behavior is the current behavior (also shows error) for when a file exists (not for directories). This isn't great at the moment because when the destination mount's write is not reliable and fails, retry doesn't work very well. Retry working is very nice because jobs are being done at file by file level so retry wouldn't have to do the full directory again. 

One could talk about doing deletion of the file when it fails but when writes are not reliable, neither are deletes and when delete fails, no more retries will be happening.

**Comment by bradyoo** [comment] 2021-04-22 18:08
Closing this task

**Closed by bradyoo** 2021-04-22 18:08 UTC
Labels: are-jobservice, type-bug
