### ISSUE TITLE
alluxio加速trino 查询提速不明显

### ISSUE THREAD

**Issue by sfwanyi** [Alluxio/alluxio#14208] opened 2021-10-08 03:11 UTC
aluxio 配置文件：
properties:
  alluxio.user.metrics.collection.enabled: true
  alluxio.debug: true
  alluxio.user.short.circuit.enabled: true
  alluxio.worker.data.server.domain.socket.as.uuid: true
  alluxio.worker.data.server.domain.socket.address: /opt/domain
  alluxio.master.journal.ufs.option.alluxio.underfs.hdfs.configuration: /secrets/hdfsConfig/core-site.xml:/secrets/hdfsConfig/hdfs-site.xml
  alluxio.master.mount.table.root.option.alluxio.underfs.version: 3.2
  alluxio.master.mount.table.root.ufs: hdfs://hdfs-namenodes:8020
  alluxio.security.authentication.type: NOSASL
  alluxio.security.authorization.permission.enabled: false
  alluxio.user.file.metadata.load.type: ONCE
  alluxio.user.file.passive.cache.enabled: true
  alluxio.user.file.readtype.default: CACHE
  alluxio.user.file.writetype.default: CACHE_THROUGH
  alluxio.user.network.data.timeout: 10min
  alluxio.user.ufs.block.read.location.policy: alluxio.client.block.policy.DeterministicHashPolicy
  alluxio.worker.allocator.class: alluxio.worker.block.allocator.RoundRobinAllocator
  alluxio.worker.evictor.class: alluxio.worker.block.evictor.LRUEvictor
  alluxio.worker.ramdisk.size: 64GB
  alluxio.worker.tieredstore.level0.alias: MEM
  alluxio.worker.tieredstore.level0.dirs.mediumtype: MEM
  alluxio.worker.tieredstore.level0.dirs.path: /dev/shm
  alluxio.worker.tieredstore.level0.dirs.quota: 64GB
  alluxio.worker.tieredstore.level0.watermark.high.ratio: "0.95"
  alluxio.worker.tieredstore.level0.watermark.low.ratio: "0.7"
  alluxio.worker.tieredstore.level1.alias: SSD
  alluxio.worker.tieredstore.level1.dirs.mediumtype: SSD
  alluxio.worker.tieredstore.level1.dirs.path: /ssd-disk
  alluxio.worker.tieredstore.level1.dirs.quota: 100GB
  alluxio.worker.tieredstore.level1.watermark.high.ratio: "0.9"
  alluxio.worker.tieredstore.level1.watermark.low.ratio: "0.7"
  alluxio.worker.tieredstore.levels: 1

shortCircuit:
  enabled: true
  policy: uuid
  size: 1Mi
  volumeType: hostPath
  hostPath: /tmp/alluxio-domain

文件缓存在alluxio中
![image](https://user-images.githubusercontent.com/10410721/136492253-06d082da-20b2-4a62-9251-617ee733bf96.png)

短路读取为0
![Uploading image.png…]()

trino查询加速不明显

**Comment by yuzhu** [comment] 2021-10-11 16:11
duplicate of #14222

**Closed by yuzhu** 2021-10-11 16:11 UTC
Labels: type-feature
