### ISSUE TITLE
Alluxio Metrics Don't Report Bytes Written

### ISSUE THREAD

**Issue by ZacBlanco** [Alluxio/alluxio#9210] opened 2019-06-04 23:23 UTC
**Alluxio Version:**
1.8.1, 2.0.0-RC2

**Describe the bug**
When we perform write operations using the CLI (or any other means), the Alluxio metrics for `Bytes Written` and `Bytes Written UFS` never get incremented in the master at `/api/v1/master`, `/metrics/json` as well as `./bin/alluxio fsadmin report metrics`

**To Reproduce**

using `MUST_CACHE` as the write type:

```bash
./bin/alluxio-start.sh local
./bin/alluxio fs copyFromLocal LICENSE /LICENSE
./bin/alluxio fs persist /LICENSE
./bin/alluxio fsadmin report metrics
```

The metrics report will report no bytes written to Alluxio or the UFS

**Expected behavior**

The command-line metrics report and the REST endpoints should be reporting the bytes written to Alluxio and/or the UFS. Currently, it always seems to be 0.

**Urgency**
minor

**Additional context**
Reported via slack community

**Comment by calvinjia** [comment] 2019-06-05 23:06
This is because persist is implemented through the job service which write the data through the job worker (as if it were a separate client) and not the Alluxio worker.
To fix this I think we would need to have metrics for job worker tasks and is more of a feature-request than a bug-fix.

**Comment by ZacBlanco** [comment] 2019-06-06 01:12
Thanks for looking into this!

I would disagree in that as it stands, the metric name implies _all_ bytes written to the UFS. It doesn't have any caveats saying it is worker-only vs job worker. I think this is misleading to the user. Under the current definition of the metric it seems like more of a bug.

Either way, thanks for clarifying this. To reiterate in my own words, in order for bytes written to the UFS to be reported, the user must use `CACHE_THROUGH` or `THROUGH` write types in order for the metrics to show up?

I'm not sure exactly how you tested either, but my "Bytes written to Alluxio" (not the UFS) also always remained at 0. Were you able to get that number to change?

**Comment by ZacBlanco** [comment] 2019-06-06 11:57
Also, another note I forgot- when I tested I used the v1.8.1 tag that doesn't include the job service. Persist operations were still not incrementing the counter.

**Comment by ferozzahid** [comment] 2019-06-06 13:23
I can confirm that using write with CACHE_THROUGH updates metrics correctly for the UFSs (verison 1.8.1).

**Comment by calvinjia** [comment] 2019-06-06 18:28
I think we both agree the metrics should be tracked, the question is whether there should be a separate set of metrics for the job service or if the job service should report metrics back to the master.

Yes, currently the metrics only track data that is written through the Alluxio worker.

I don't see a `bytes written to Alluxio` metric, but I didn't have any Alluxio write metrics because all my writes to Alluxio were short circuit.

**Comment by rastogiasr** [comment] 2019-07-02 01:39
Closing the issue - @calvinjia please open another issue to provide job service metrics.

**Closed by rastogiasr** 2019-07-02 01:39 UTC
Labels: type-bug
