### ISSUE TITLE
hdfs under filesystem not support impersonate

### ISSUE THREAD

**Issue by gjhkael** [Alluxio/alluxio#14866] opened 2022-01-18 10:46 UTC
Now, alluxio request hdfs is use the user that login from kerberos, it will leads to HDFS permission leak for alluxio aways use super user to access hdfs. So if hdfs under filesystem support impersonate, it seems solve the problem。

**Comment by apc999** [comment] 2022-01-18 19:39
duplicate of https://github.com/Alluxio/alluxio/issues/14867

**Closed by apc999** 2022-01-18 19:39 UTC
Labels: type-feature
